services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce_mysql_dw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce_dw
      MYSQL_USER: etl_user
      MYSQL_PASSWORD: etl_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "etl_user", "-petl_password"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
